### ISSUE TITLE
Prometheus config

### ISSUE THREAD

**Issue by luckenbach** [lampwins/junos_exporter#10]
Reviewing the docs it indicates that the Junos Exporter 'follows many of the same tenants as the snmp exporter'

Setting mine up like so
```
 scrape_configs:
    - job_name: 'testjunos'
      static_configs:
        - targets:
          - 10.62.4.11  
      params:
        module: [junos_test]
```
does not net in valid queries getting passed to the exporter, i assume the reLabel settings are required but im not sure what should go in there. Any help would be appriciated

**Comment by lampwins** [comment]
@luckenbach thanks for pointing out the vagueness of the docs, I will try to update them with some more substantial information. As for the scrape config, here is an example from mine:
```yaml
- job_name: 'junos_exporter-core'
    scrape_interval: 30s
    scrape_timeout: 30s
    dns_sd_configs:
      - names:
          - 'all.core.routers.example.com'
    metrics_path: /metrics
    params:
      module: [core]
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):.*'
        target_label: __param_target
        replacement: '$1'
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: junos-exporter.example.com:9665  # junos exporter.
      - source_labels: [__address__]
        target_label: exporter_node
```

Basically you are using relabeling to tell prometheus to "scrape" the junos_exporter with the actual target and module passed as url query parameters, instead of the target directly.

Also I am using dns srv records as targets, so you would replace that with your static targets.
